dataset_name: 'dogs'
dataset_root_path: '../../data/dogs'
df_train: 'train.csv'
df_trainval: train_val.csv
df_val: 'val.csv'
df_test: 'test.csv'
folder_train: 'Images'
folder_val: 'Images'
folder_test: 'Images'
df_classid_classname: 'classid_classname.csv'
