dataset_name: 'inat17'
dataset_root_path: '../../data/inat17'
df_train: 'train.csv'
df_trainval: train_val.csv
df_val: 'val.csv'
df_test: 'test.csv'
folder_train: 'train_val_images'
folder_val: 'train_val_images'
folder_test: 'train_val_images'
df_classid_classname: 'classid_classname.csv'
